apiVersion: apps/v1
kind: Deployment
metadata:
  name: marks-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marks-api
  template:
    metadata:
      labels:
        app: marks-api
    spec:
      containers:
      - name: marks-api
        image: 10.131.103.92:8090/kp1/marks-api:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
